FROM node:22-alpine

WORKDIR /app

COPY website/package.json /app
COPY website/package-lock.json /app

RUN npm install

COPY website /app

ARG NODE_ENV=ci

RUN npm run build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

ENTRYPOINT ["node", ".output/server/index.mjs"]
