version: "3"

services:
  postgres:
    networks:
      - storywise
    hostname: postgres
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: testing
    ports:
      - "5444:5432"

  timescaledb:
    networks:
      - storywise
    hostname: timescaledb
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_LOGGING_COLLECTOR: "on"
      POSTGRES_LOGGING_DIRECTORY: "/var/log/postgresql"
      POSTGRES_LOGGING_FILENAME: "postgresql.log"
      POSTGRES_LOGGING_TRUNCATE_ON_ROTATION: "on"
      POSTGRES_LOGGING_ROTATION_AGE: "1d"
      POSTGRES_LOGGING_ROTATION_SIZE: "10MB"
      POSTGRES_LOGGING_MIN_MESSAGES: "INFO"
      POSTGRES_LOGGING_ERROR_VERBOSITY: "default"
      POSTGRES_LOGGING_STDERR: "on"
      POSTGRES_LOGGING_SYSLOG: "off"
    ports:
      - "5566:5432"

networks:
  storywise:
    external: true
