apiVersion: v1
kind: ConfigMap
metadata:
  namespace: storywise
  name: storywise-demo
data:
  API_BASE_URL: http://localhost:3777
  ALLOWED_ORIGIN: "*"
  TIMESCALE_ENABLED: "true"
  PORT: "3777"
  POSTGRES_HOST: storywise-demo-postgres.storywise.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_OPTIONS: "sslmode=require binary_parameters=yes"
