# Obviously, this is a demo secret and should not be used in a real deployment
apiVersion: v1
kind: Secret
metadata:
  namespace: storywise
  name: storywise-demo
type: Opaque
stringData:
  STORYWISE_USERNAME: demo
  STORYWISE_PASSWORD: thisshouldbeasecret
  POSTGRES_USER: storywise
  POSTGRES_DB: storywise-database
  POSTGRES_PASSWORD: storywise-password
