name: PR Checks

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@master

      - name: npm install
        run: npm install

      - name: npm run typecheck
        run: npm run typecheck

      - name: npm run build
        run: npm run build

  build-test-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.x]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@master

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.ci.yaml"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build
        working-directory: ./api-go

      - name: Wait for postgres
        run: |
          while ! nc -z 127.0.0.1 5566; do
            sleep 0.1
          done

          sleep 5

      - name: Test
        run: go test
        working-directory: ./api-go
