name: Automated tagging
on:
  workflow_call:
    inputs:
      github-repository:
        type: string
        description: "Repository to tag"
        required: true
      image-name:
        type: string
        description: "Name of the image to tag"
        required: true
      image-tag:
        type: string
        description: "Tag to use for the image"
        required: true
    secrets:
      ssh-key:
        description: "SSH key to use for pushing to the repo"
        required: true
      known-hosts:
        description: "Known hosts to use for pushing to the repo"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ssh-key }}
          known_hosts: ${{ secrets.known-hosts }}

      - name: Update repo
        run: |
          # VARIABLES

          # SETUP
          git config --global user.email "hey@joinstorywise.com"
          git config --global user.name "Storywise Robot"
          git clone ${{inputs.github-repository}} kubernetes
          cd kubernetes

          # CHANGES
          find ./${{inputs.image-name}} -type f -name '*.yaml' -exec sed -i "s/${{inputs.image-name}}:.*$/${{inputs.image-name}}:${{ inputs.image-tag }}/" {} \;

          # PUSH
          git remote set-url origin ${{inputs.github-repository}}
          git add .
          git commit -m "Release ${{inputs.image-name}} version ${{ inputs.image-tag }}"
          git push
